version: "3.1"
services:
    #PHP Service
    app:
      build:
        context: ./web
        dockerfile: Dockerfile
      container_name: app
      working_dir: /application
      volumes:
        - ./web:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    #Nginx Service
    web:
      image: nginx:alpine
      container_name: web
      working_dir: /application
      volumes:
          - ./web:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    #MySQL Service
    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /application
      volumes:
        - ./web:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=e-briefing
        - MYSQL_USER=e-brief-user
        - MYSQL_PASSWORD=secret
      ports:
        - "8082:3306"
