###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: e-brief-mailhog
      ports:
        - "8081:8025"

    mysql:
      image: mysql:5.7
      container_name: e-brief-mysql
      working_dir: /application
      volumes:
        - ./web:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=e-briefing
        - MYSQL_USER=e-brief-user
        - MYSQL_PASSWORD=secret
      ports:
        - "8082:3306"

    web:
      image: nginx:alpine
      container_name: e-brief-webserver
      working_dir: /application
      volumes:
          - ./web:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    app:
      build: docker/php-fpm
      container_name: e-brief-php-fpm
      working_dir: /application
      volumes:
        - ./web:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

